apiVersion: v1
kind: Service
metadata:
  name: img-proc-api-svc
  labels:
    app: img-proc-api-svc
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 8082
  selector:
    app: img-proc-api-svc
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: img-proc-api-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: img-proc-api-svc
        tier: backend
    spec:
      containers:
      - name: img-proc-api-svc
        image: img-proc-api-svc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8082
        env:
        - name: MYSQL_ENDPOINT
          value: mysql
        - name: MYSQL_USER
          value: dev
        - name: MYSQL_PASSWORD
          value: 123456
        - name: MYSQL_DATABASE
          value: spi
