apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8081
  selector:
    app: auth-svc
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-svc
        tier: backend
    spec:
      containers:
      - name: auth-svc
        image: gseverina/auth-svc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_ENDPOINT
          value: mysql
        - name: MYSQL_USER
          value: dev
        - name: MYSQL_PASSWORD
          value: 123456
        - name: MYSQL_DATABASE
          value: spi
