apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  labels:
    app: storage-svc
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 8083
  selector:
    app: storage-svc
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-svc
        tier: backend
    spec:
      containers:
      - name: storage-svc
        image: storage-svc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8083
