version: "2"
services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-svc

  auth-svc:
    build: auth-svc
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      MYSQL_ENDPOINT: mysql
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spt

  jobs-frontend-svc:
    build: jobs-frontend-svc
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      MYSQL_ENDPOINT: mysql
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spt

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: spt