global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090', 'localhost:9323']
        labels:
          group: 'prometheus'

  - job_name: "node"
    static_configs:
      - targets: ['localhost:9100']
