- name: install docker engine
  #hosts: aws-01
  hosts: intel-cloud02
  become: true
  environment:
    http_proxy: http://proxy-us.intel.com:911
    https_proxy: http://proxy-us.intel.com:911
  tasks:
    - name: install curl
      apt: name=curl update_cache=yes
      when: ansible_os_family == "Debian"

    - name: install redsocks
      apt: name=redsocks update_cache=yes
      when: ansible_os_family == "Debian"

    - service: name=redsocks state=stopped
      when: ansible_os_family == "Debian"

    - name: copy enable_socks sh
      copy: src=./files/enable_socks.sh dest=/tmp/enable_socks.sh mode="u+rwx,g+rx,o+rx"
      when: ansible_os_family == "Debian"

    - name: copy redsocks.conf
      copy: src=./files/redsocks.conf dest=/tmp/redsocks.conf mode=0644
      when: ansible_os_family == "Debian"

    - name: execute redsocks
      command: /tmp/enable_socks.sh
      when: ansible_os_family == "Debian"

    - name: execute command curl to download docker engine installer
      command: curl -o install.sh -fsSL https://get.docker.com/

    - name: set execution permissions to installer script file
      file: path=./install.sh mode="u+rwx,g+rx,o+rx"

    - name: execute command to run the installer script
      command: ./install.sh

    - service: name=docker state=restarted
