# ssh SG
- name: Create ssh Security Group
  ec2_group:
    name: "{{ vpc_name }}-sg-ssh"
    description: "Allows external SSH access"
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
  register: my_ssh_sg

- name: Set ssh SG ID
  set_fact:
    ssh_sg_id: "{{ my_ssh_sg.group_id }}"

- name: Tag Name for ssh Security Group
  ec2_tag:
    region: "{{ vpc_region }}"
    resource: "{{ ssh_sg_id }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-sg-ssh"
      project: "{{ project_name }}"
      environment: "{{ env_name }}"
